name: 100x-sem-1-assignment

services:
  postgres:
    image: postgres
    container_name: 100x-sem-1-assignment-postgres
    environment:
      POSTGRES_DB: 100x-sem-1-assignment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - 100x-sem-1-assignment_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  100x-sem-1-assignment_postgres_data:
